[2024-09-12T19:00:03.418+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T19:00:03.432+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_automation_dag.poll_step_layer manual__2024-09-12T18:59:56.619655+00:00 [queued]>
[2024-09-12T19:00:03.438+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_automation_dag.poll_step_layer manual__2024-09-12T18:59:56.619655+00:00 [queued]>
[2024-09-12T19:00:03.439+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-12T19:00:03.446+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): poll_step_layer> on 2024-09-12 18:59:56.619655+00:00
[2024-09-12T19:00:03.452+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2089) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-12T19:00:03.454+0000] {standard_task_runner.py:72} INFO - Started process 2091 to run task
[2024-09-12T19:00:03.455+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'snowflake_automation_dag', 'poll_step_layer', 'manual__2024-09-12T18:59:56.619655+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/***_emr_spark_s3_snowflake.py', '--cfg-path', '/tmp/tmpvh8435mz']
[2024-09-12T19:00:03.458+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask poll_step_layer
[2024-09-12T19:00:03.501+0000] {task_command.py:467} INFO - Running <TaskInstance: snowflake_automation_dag.poll_step_layer manual__2024-09-12T18:59:56.619655+00:00 [running]> on host 70476fe7f1d5
[2024-09-12T19:00:03.579+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='snowflake_automation_dag' AIRFLOW_CTX_TASK_ID='poll_step_layer' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T18:59:56.619655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T18:59:56.619655+00:00'
[2024-09-12T19:00:03.581+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T19:00:03.600+0000] {logging_mixin.py:190} INFO - The cluster id : j-3I4TYH5DJLIOO
[2024-09-12T19:00:03.601+0000] {logging_mixin.py:190} INFO - The emr step id : s-01570913VOVEUDBBM0EL
[2024-09-12T19:00:03.901+0000] {logging_mixin.py:190} INFO - The step is PENDING
[2024-09-12T19:00:13.593+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-12T19:00:13.600+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-12T19:00:13.603+0000] {process_utils.py:132} INFO - Sending 15 to group 2091. PIDs of all processes in the group: [2091]
[2024-09-12T19:00:13.604+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2091
[2024-09-12T19:00:13.606+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-12T19:00:13.653+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T19:00:13.699+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2091, status='terminated', exitcode=0, started='19:00:03') (2091) terminated with exit code 0
